name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  claude-review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            **/*.swift
            **/*.h
            **/*.m
          separator: ","
          
      - name: Claude Code Review
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/github-script@v7
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        with:
          script: |
            const { execSync } = require('child_process');
            
            // Get PR diff
            const diff = execSync(`git diff origin/main...HEAD -- ${process.env.CHANGED_FILES.split(',').join(' ')}`, { encoding: 'utf8' });
            
            if (!diff.trim()) {
              console.log('No relevant changes to review');
              return;
            }
            
            // Call Claude API
            const response = await fetch('https://api.anthropic.com/v1/messages', {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                'x-api-key': process.env.ANTHROPIC_API_KEY,
                'anthropic-version': '2023-06-01'
              },
              body: JSON.stringify({
                model: 'claude-3-sonnet-20240229',
                max_tokens: 4000,
                messages: [{
                  role: 'user',
                  content: `Please review this Swift/iOS code changes and provide constructive feedback. Focus on:
                  - Code quality and best practices
                  - Potential bugs or issues
                  - Performance considerations
                  - iOS/Swift specific patterns
                  - Security concerns
                  
                  Here's the diff:
                  \`\`\`diff
                  ${diff}
                  \`\`\`
                  
                  Provide your review in markdown format with specific line references where possible.`
                }]
              })
            });
            
            const result = await response.json();
            
            if (result.error) {
              console.error('Claude API error:', result.error);
              return;
            }
            
            // Post comment on PR
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: `## 🤖 Claude Code Review\n\n${result.content[0].text}`
            });